import * as XLSX from "xlsx";
import {
  fmt,
  type Analysis,
  type Subject,
} from "@/lib/analysis";

export type ExportMeta = {
  institution: string;
  department: string;
  title: string;
  year: string;
  semester: string;
  batch: string;
  section: string;
};

export function exportAnalysisSheet(
  a: Analysis,
  subjects: Subject[],
  meta: ExportMeta,
) {
  const wb = XLSX.utils.book_new();
  const catCounts = a.categoryCounts;
  const hostC = (catCounts["C-H-B"] ?? 0) + (catCounts["C-H-G"] ?? 0);
  const dayC = (catCounts["C-DS-B"] ?? 0) + (catCounts["C-DS-G"] ?? 0);
  const hostM = (catCounts["M-H-B"] ?? 0) + (catCounts["M-H-G"] ?? 0);
  const dayM = (catCounts["M-DS-B"] ?? 0) + (catCounts["M-DS-G"] ?? 0);

  const front: (string | number)[][] = [
    [meta.institution],
    [meta.department],
    [meta.title],
    [
      "YEAR  :",
      meta.year,
      "SEMESTER:",
      meta.semester,
      "BATCH:",
      "",
      "BATCH:",
      meta.batch,
      "",
      "",
      "SECTION:",
      "",
      "",
      meta.section,
    ],
    [],
    [
      "S.No.",
      "PARTICULARS",
      "",
      "",
      "",
      "",
      "TOTAL",
      "COUNSELLING",
      "",
      "",
      "",
      "MANAGEMENT",
      "",
      "",
      "",
    ],
    [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      `HOSTELLER(${hostC})`,
      "",
      `DAY SCHOLAR(${dayC})`,
      "",
      `HOSTELLER(${hostM})`,
      "",
      `DAY SCHOLAR(${dayM})`,
      "",
    ],
    ["", "", "", "", "", "", "", "BOYS", "GIRLS", "BOYS", "GIRLS", "BOYS", "GIRLS", "BOYS", "GIRLS"],
    ...a.particulars.map((p, i) => [
      i + 1,
      p.label.toUpperCase(),
      "",
      "",
      "",
      "",
      p.total,
      p.byCategory["C-H-B"],
      p.byCategory["C-H-G"],
      p.byCategory["C-DS-B"],
      p.byCategory["C-DS-G"],
      p.byCategory["M-H-B"],
      p.byCategory["M-H-G"],
      p.byCategory["M-DS-B"],
      p.byCategory["M-DS-G"],
    ]),
    [
      a.particulars.length + 1,
      "PASS PERCENTAGE",
      "",
      "",
      "",
      "",
      Number(fmt(a.passPercent, 2)),
    ],
    [],
    ["TOPPER LIST"],
    ["", "S.NO", "REG.NO", "PHOTO", "STUDENTS NAME", "", "", "", "", "TOTAL", "", "PASS %", "", "RANK"],
    ...a.toppers.slice(0, 3).map((r, i) => [
      "",
      i + 1,
      r.student.reg,
      "",
      r.student.name,
      "",
      "",
      "",
      "",
      r.total,
      "",
      Number(fmt(r.percent, 2)),
      "",
      i === 0 ? "I" : i === 1 ? "II" : "III",
    ]),
    [],
    ["SUBJECT WISE PERFORMANCE"],
    [
      "",
      "S.NO",
      "SUB CODE",
      "SUBJECT NAME",
      "",
      "STAFF NAME",
      "",
      "",
      "",
      "APPEARED",
      "ABSENT",
      "PASSED",
      "FAILED",
      "PASS %",
    ],
    ...a.subjectStats.map((s, i) => [
      "",
      i + 1,
      s.subject.code,
      s.subject.name,
      "",
      s.subject.staff || "",
      "",
      "",
      "",
      s.appeared,
      s.absent,
      s.passed,
      s.failed,
      Number(fmt(s.passPercent, 2)),
    ]),
    [],
    [],
    ["", "PREPARED BY", "", "", "HOD", "", "", "", "", "VICE PRINCIPAL", "", "", "", "PRINCIPAL"],
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(front), "FRONT");

  const subjectHeaders = subjects.map((s) => `${s.code} & ${s.name}`);
  const markHeader = [
    "SL.NO",
    "REG. NO.",
    "STUDENT'S NAME",
    "B/G",
    "C/M",
    "H/DS",
    "E/T",
    ...subjectHeaders,
    "TOTAL",
    "PASS %",
    "ARREAR COUNT",
  ];

  const rowFor = (r: (typeof a.results)[0], i: number) => [
    i + 1,
    r.student.reg,
    r.student.name,
    r.student.gender,
    r.student.quota,
    r.student.stay,
    "E",
    ...r.student.marks.map((m) => (m === null ? "" : m)),
    r.total,
    Number(fmt(r.percent, 2)),
    r.arrears,
  ];

  const sorted = [...a.results].sort((x, y) =>
    x.student.reg.localeCompare(y.student.reg),
  );

  const markSheet: (string | number)[][] = [
    [meta.institution],
    [meta.department],
    ["ASSESSMENT RESULT ANALYSIS"],
    [
      "YEAR  :",
      meta.year,
      "SEMESTER:",
      meta.semester,
      "BATCH:",
      "",
      "BATCH:",
      meta.batch,
      "",
      "",
      "",
      "SECTION:",
      "",
      "",
      meta.section,
    ],
    [],
    markHeader,
    ...sorted.map((r, i) => rowFor(r, i)),
    [],
    [
      "Total No. of Students",
      "",
      "",
      "",
      "",
      "",
      "",
      ...subjects.map(() => a.totalStudents),
    ],
    [
      "No. of Students Present",
      "",
      "",
      "",
      "",
      "",
      "",
      ...a.subjectStats.map((s) => s.appeared),
    ],
    [
      "No. of Students Absent",
      "",
      "",
      "",
      "",
      "",
      "",
      ...a.subjectStats.map((s) => s.absent),
    ],
    [
      "No. of Students Pass",
      "",
      "",
      "",
      "",
      "",
      "",
      ...a.subjectStats.map((s) => s.passed),
    ],
    [
      "No. of Students fail",
      "",
      "",
      "",
      "",
      "",
      "",
      ...a.subjectStats.map((s) => s.failed),
    ],
    [
      "PASS%",
      "",
      "",
      "",
      "",
      "",
      "",
      ...a.subjectStats.map((s) => Number(fmt(s.passPercent, 2))),
    ],
    [],
    [meta.institution],
    [meta.department],
    ["ASSESSMENT RESULT ANALYSIS"],
    ["ALL CLEAR STUDENTS"],
    markHeader,
    ...sorted.filter((r) => r.arrears === 0).map((r, i) => rowFor(r, i)),
    ["ONE SUBJECTS ARREAR STUDENTS"],
    markHeader,
    ...sorted.filter((r) => r.arrears === 1).map((r, i) => rowFor(r, i)),
    ["TWO SUBJECTS ARREAR STUDENTS"],
    markHeader,
    ...sorted.filter((r) => r.arrears === 2).map((r, i) => rowFor(r, i)),
    ["THREE & ABOVE SUBJECTS ARREAR STUDENTS"],
    markHeader,
    ...sorted.filter((r) => r.arrears >= 3).map((r, i) => rowFor(r, i)),
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(markSheet), "MARK");
  XLSX.writeFile(
    wb,
    `Result_Analysis_${meta.batch}_${meta.section}.xlsx`,
  );
}
